"use client";
import sample from "@/data/sample-pr.json";
import ledger from "@/data/trust-ledger.json";
import { scoreHunk } from "@/lib/risk";
import { ledgerAccuracy } from "@/lib/trust";
import type { Category, Decision, LedgerRun } from "@/lib/types";
import { useMemo, useState } from "react";

const palette = { low: "bg-emerald-100 text-emerald-900", medium: "bg-amber-100 text-amber-900", high: "bg-orange-100 text-orange-900", critical: "bg-rose-100 text-rose-900" };
export default function Home() {
  const hunks = sample.files.flatMap((file) => file.hunks.map((hunk) => ({ ...hunk, path: file.path, assessment: scoreHunk(file.path, hunk.diff, hunk.category as Category, hunk.riskReason) })));
  const [decisions, setDecisions] = useState<Record<string, Decision>>({});
  const [comments, setComments] = useState<Record<string, string>>({});
  const [aiOn, setAiOn] = useState(false); const [aiReasons, setAiReasons] = useState<Record<string, string>>({}); const [notice, setNotice] = useState("");
  const summary = useMemo(() => hunks.reduce((acc, h) => { const decision = decisions[h.id] ?? "pending"; acc[decision]++; if (decision !== "approved") acc.netRisk += h.assessment.score; return acc; }, { approved: 0, rejected: 0, commented: 0, pending: 0, netRisk: 0 }), [decisions, hunks]);
  const accuracy = ledgerAccuracy(ledger as LedgerRun[]);
  const decide = (id: string, value: Decision) => setDecisions((all) => ({ ...all, [id]: value }));
  const sharpen = async (id: string, category: string, reason: string) => { const response = await fetch("/api/explain", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ category, reason }) }); const data = await response.json(); if (response.ok) setAiReasons((all) => ({ ...all, [id]: data.reason })); else setNotice(data.error); };
  const exportJson = () => { const content = JSON.stringify({ exportedAt: new Date().toISOString(), decisions: hunks.map((h) => ({ hunkId: h.id, path: h.path, score: h.assessment.score, decision: decisions[h.id] ?? "pending", comment: comments[h.id] ?? "" })) }, null, 2); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([content], { type: "application/json" })); link.download = "review-matrix-decisions.json"; link.click(); URL.revokeObjectURL(link.href); };
  return <main className="mx-auto max-w-6xl p-4 sm:p-8">
    <header className="mb-7 flex flex-col gap-4 border-b-2 border-slate-900 pb-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-1 text-xs font-bold tracking-[.2em] text-blue-700">AGENTIC PR REVIEW</p><h1 className="text-4xl font-black tracking-tight">Review Matrix</h1><p className="mt-2 text-slate-600">Make a bounded call on every AI-authored change.</p></div><button onClick={exportJson} className="rounded bg-slate-900 px-4 py-2 font-bold text-white">Export decisions JSON</button></header>
    <section aria-label="Review summary" className="mb-7 grid grid-cols-2 gap-3 sm:grid-cols-5"><Metric label="Approved" value={summary.approved} /><Metric label="Redirected" value={summary.rejected} /><Metric label="Needs comment" value={summary.commented} /><Metric label="Unreviewed" value={summary.pending} /><Metric label="Net risk" value={summary.netRisk} /></section>
    <section className="mb-7 rounded-lg border border-slate-300 bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-black">Trust Ledger</h2><p className="text-sm text-slate-600"><strong>{accuracy.percentage}% accuracy</strong> — {accuracy.correct} correct risk/outcome agreements across {accuracy.total} past predictions.</p></div><span className="rounded-full bg-blue-100 px-3 py-1 text-sm font-bold text-blue-900">Bundled history</span></div></section>
    <label className="mb-5 flex w-fit items-center gap-3 rounded border border-slate-300 bg-white px-3 py-2 text-sm font-bold"><input type="checkbox" checked={aiOn} onChange={(e) => setAiOn(e.target.checked)} /> Sharpen with AI <span className="font-normal text-slate-500">(reason only)</span></label>
    {notice && <p role="status" className="mb-4 rounded bg-amber-100 p-3 text-sm text-amber-950">{notice}</p>}
    <div className="space-y-5">{sample.files.map((file) => <section key={file.path} className="overflow-hidden rounded-lg border border-slate-300 bg-white"><h2 className="border-b border-slate-200 bg-slate-50 px-4 py-3 font-mono text-sm font-bold">{file.path}</h2>{file.hunks.map((hunk) => { const assessed = scoreHunk(file.path, hunk.diff, hunk.category as Category, hunk.riskReason); const decision = decisions[hunk.id] ?? "pending"; return <article key={hunk.id} className="p-4"><div className="mb-3 flex flex-wrap items-center gap-2"><span className="rounded px-2 py-1 text-xs font-black uppercase tracking-wide bg-slate-100">{hunk.category}</span><span className={`rounded px-2 py-1 text-xs font-black uppercase ${palette[assessed.level]}`}>{assessed.level} · {assessed.score}/100</span><span className="text-xs text-slate-500">{decision}</span></div><pre className="mb-3 rounded bg-slate-950 p-3 text-sm leading-6 text-slate-100">{hunk.diff}</pre><p className="mb-3 text-sm"><strong>Why:</strong> {aiReasons[hunk.id] ?? assessed.reason}</p><div className="flex flex-wrap gap-2"><button onClick={() => decide(hunk.id, "approved")} className="rounded bg-emerald-700 px-3 py-2 text-sm font-bold text-white" aria-label={`Approve ${hunk.id}`}>Approve</button><button onClick={() => decide(hunk.id, "rejected")} className="rounded bg-rose-700 px-3 py-2 text-sm font-bold text-white" aria-label={`Redirect ${hunk.id}`}>Redirect</button><button onClick={() => decide(hunk.id, "commented")} className="rounded border border-slate-400 px-3 py-2 text-sm font-bold" aria-label={`Comment on ${hunk.id}`}>Comment</button>{aiOn && <button onClick={() => sharpen(hunk.id, hunk.category, assessed.reason)} className="rounded border border-blue-700 px-3 py-2 text-sm font-bold text-blue-800">Sharpen reason</button>}</div>{decision === "commented" && <label className="mt-3 block text-sm font-bold">Reviewer note<textarea value={comments[hunk.id] ?? ""} onChange={(e) => setComments((all) => ({ ...all, [hunk.id]: e.target.value }))} className="mt-1 block w-full rounded border border-slate-300 p-2 font-normal" rows={2} /></label>}</article>})}</section>)}</div>
  </main>;
}
function Metric({ label, value }: { label: string; value: number }) { return <div className="rounded border border-slate-300 bg-white p-3"><p className="text-xs font-bold uppercase text-slate-500">{label}</p><p className="text-2xl font-black">{value}</p></div>; }
