"use client";

export { default } from "./review-matrix";

/* Legacy page implementation retained below while the enhanced review surface lives in review-matrix.tsx.

import sample from "@/data/sample-pr.json";
import ledger from "@/data/trust-ledger.json";
import { scoreHunk } from "@/lib/risk";
import { requestChangesGuide } from "@/lib/review";
import { ledgerAccuracy, weightedTrust } from "@/lib/trust";
import type { Category, Decision, LedgerRun, RiskLevel, SamplePr } from "@/lib/types";
import { useMemo, useState } from "react";

const categories: Category[] = ["auth", "db", "secrets", "deps", "logic", "performance", "migration", "pii"];
const tone: Record<RiskLevel, string> = { low: "bg-emerald-400/15 text-emerald-200 border-emerald-400/25", medium: "bg-amber-400/15 text-amber-200 border-amber-400/25", high: "bg-orange-400/15 text-orange-200 border-orange-400/25", critical: "bg-rose-400/15 text-rose-200 border-rose-400/25" };
const catIcon: Record<Category, string> = { auth: "◈", db: "◫", secrets: "⌘", deps: "◌", logic: "◇", performance: "↗", migration: "⇄", pii: "◎" };
type ReviewHunk = { id: string; path: string; category: Category; diff: string; riskReason: string; assessment: ReturnType<typeof scoreHunk> };

function deriveHunks(pr: SamplePr): ReviewHunk[] { return pr.files.flatMap((file) => file.hunks.map((hunk) => ({ ...hunk, path: file.path, category: hunk.category as Category, assessment: scoreHunk(file.path, hunk.diff, hunk.category as Category, hunk.riskReason) }))); }

export default function Home() {
  const [review, setReview] = useState<SamplePr>(sample as SamplePr);
  const [decisions, setDecisions] = useState<Record<string, Decision>>({});
  const [comments, setComments] = useState<Record<string, string>>({});
  const [activeCategory, setActiveCategory] = useState<Category | "all">("all");
  const [query, setQuery] = useState(""); const [prUrl, setPrUrl] = useState(""); const [status, setStatus] = useState("Bundled demonstration PR loaded — deterministic scoring is active.");
  const [loading, setLoading] = useState(false); const [aiOn, setAiOn] = useState(false); const [aiReasons, setAiReasons] = useState<Record<string, string>>({}); const [requesting, setRequesting] = useState<ReviewHunk | null>(null);
  const hunks = useMemo(() => deriveHunks(review), [review]);
  const visible = hunks.filter((h) => (activeCategory === "all" || h.category === activeCategory) && `${h.path} ${h.diff}`.toLowerCase().includes(query.toLowerCase()));
  const summary = useMemo(() => hunks.reduce((acc, h) => { const d = decisions[h.id] ?? "pending"; acc[d]++; if (d !== "approved") acc.netRisk += h.assessment.score; return acc; }, { approved: 0, rejected: 0, commented: 0, request_changes: 0, pending: 0, netRisk: 0 }), [decisions, hunks]);
  const trust = weightedTrust(ledger as LedgerRun[]); const accuracy = ledgerAccuracy(ledger as LedgerRun[]);
  const distribution = (["low", "medium", "high", "critical"] as RiskLevel[]).map((level) => ({ level, count: hunks.filter((h) => h.assessment.level === level).length }));
  const decide = (hunk: ReviewHunk, decision: Decision) => { setDecisions((all) => ({ ...all, [hunk.id]: decision })); if (decision === "request_changes") setRequesting(hunk); };
  const sharpen = async (h: ReviewHunk) => { const response = await fetch("/api/explain", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ category: h.category, reason: h.assessment.reason }) }); const data = await response.json(); if (response.ok) setAiReasons((all) => ({ ...all, [h.id]: data.reason })); else setStatus(data.error); };
  const loadPr = async () => { if (!prUrl.trim()) { setStatus("Paste a public GitHub pull request URL to try live loading."); return; } setLoading(true); try { const response = await fetch(`/api/github-pr?url=${encodeURIComponent(prUrl)}`); const data = await response.json(); if (response.ok) { setReview(data.pr as SamplePr); setDecisions({}); setComments({}); setStatus(`Loaded ${data.pr.files.length} files from GitHub. Scoring remains local and deterministic.`); } else { setReview(sample as SamplePr); setStatus(`${data.error} Showing bundled demonstration PR instead.`); } } catch { setReview(sample as SamplePr); setStatus("Could not reach GitHub. Showing bundled demonstration PR instead."); } finally { setLoading(false); } };
  const exportJson = () => { const content = JSON.stringify({ product: "Review Matrix", exportedAt: new Date().toISOString(), decisions: hunks.map((h) => { const d = decisions[h.id] ?? "pending"; return { hunkId: h.id, path: h.path, category: h.category, score: h.assessment.score, decision: d, comment: comments[h.id] ?? "", requestChanges: d === "request_changes" ? requestChangesGuide(h.assessment) : undefined }; }) }, null, 2); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([content], { type: "application/json" })); link.download = "review-matrix-decisions.json"; link.click(); URL.revokeObjectURL(link.href); };
  const requestGuide = requesting ? requestChangesGuide(requesting.assessment) : null;
  return <main className="mx-auto max-w-7xl px-4 py-5 sm:px-6 lg:px-8">
    <header className="glass mb-5 flex flex-col gap-4 rounded-3xl px-5 py-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-gradient-to-br from-blue-500 to-cyan-300 text-xl font-black text-slate-950">RM</div><div><h1 className="text-xl font-black tracking-tight">Review Matrix</h1><p className="text-sm text-cyan-200">AI-Powered Pull Request Risk Intelligence</p></div></div><button onClick={exportJson} className="rounded-xl bg-cyan-300 px-4 py-2.5 text-sm font-bold text-slate-950 transition hover:bg-cyan-200">⇩ Export review JSON</button></header>
    <section className="mb-5 grid gap-5 lg:grid-cols-[1fr_290px]"><div className="glass rounded-3xl p-5"><p className="text-xs font-bold tracking-[.2em] text-cyan-300">REVIEW COMMAND CENTER</p><h2 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Give every agent change<br /><span className="text-slate-400">a visible risk boundary.</span></h2><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300">Review Matrix evaluates each hunk with transparent rules, lets reviewers route decisions, and keeps an auditable trust signal close to the diff.</p><div className="mt-5 flex flex-col gap-2 sm:flex-row"><label className="sr-only" htmlFor="pr-url">GitHub pull request URL</label><input id="pr-url" value={prUrl} onChange={(e) => setPrUrl(e.target.value)} onKeyDown={(e) => e.key === "Enter" && loadPr()} placeholder="Paste GitHub PR URL (owner/repo/pull/42)" className="min-w-0 flex-1 rounded-xl border border-slate-600 bg-slate-950/60 px-4 py-3 text-sm placeholder:text-slate-500" /><button onClick={loadPr} disabled={loading} className="rounded-xl border border-cyan-300/40 bg-cyan-300/10 px-4 py-3 text-sm font-bold text-cyan-100 transition hover:bg-cyan-300/20 disabled:opacity-60">{loading ? "Loading…" : "Load PR"}</button></div><p role="status" className="mt-3 text-xs text-slate-400">● {status}</p></div><aside className="glass rounded-3xl p-5"><p className="text-xs font-bold tracking-[.16em] text-slate-400">WEIGHTED TRUST</p><div className="mt-3 flex items-end gap-2"><strong className="text-5xl font-black text-cyan-200">{trust.score}</strong><span className="mb-1 text-lg text-slate-400">/100</span><span className="mb-2 text-xs font-bold text-emerald-300">↗ {trust.trend}</span></div><p className="mt-2 text-xs leading-5 text-slate-400">{accuracy.correct}/{accuracy.total} historical agreements. Newer outcomes carry more weight.</p></aside></section>
    <section aria-label="Review summary" className="mb-5 grid grid-cols-2 gap-3 lg:grid-cols-5"><Stat label="Approved" value={summary.approved} accent="text-emerald-200" /><Stat label="Redirected" value={summary.rejected} accent="text-orange-200" /><Stat label="Changes requested" value={summary.request_changes} accent="text-rose-200" /><Stat label="Unreviewed" value={summary.pending} accent="text-slate-200" /><Stat label="Net risk" value={summary.netRisk} accent="text-cyan-200" /></section>
    <section className="mb-5 grid gap-5 xl:grid-cols-[1fr_320px]"><div className="glass rounded-3xl p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-bold">Risk distribution</h2><p className="text-xs text-slate-400">Live distribution across loaded hunks</p></div><span className="text-2xl">◔</span></div><div className="grid grid-cols-4 gap-3">{distribution.map(({ level, count }) => <div key={level} className="rounded-2xl bg-slate-950/45 p-3"><div className={`mb-3 h-1.5 rounded-full ${tone[level].split(" ")[0]}`} /><p className="text-xl font-black">{count}</p><p className="text-xs capitalize text-slate-400">{level}</p></div>)}</div></div><aside className="glass rounded-3xl p-5"><h2 className="font-bold">Trust calculation</h2><div className="mt-3 space-y-2 text-xs">{Object.entries(trust.breakdown).map(([window, item]) => <div className="flex justify-between border-b border-slate-700/50 pb-2" key={window}><span className="capitalize text-slate-400">{window === "24h" ? "Last 24 hours" : `Last ${window}`}</span><span>{item.correct}/{item.total} × {item.weight}</span></div>)}</div></aside></section>
    <section className="mb-5 grid gap-5 xl:grid-cols-[230px_1fr_330px]"><aside className="glass h-fit rounded-3xl p-4"><h2 className="mb-3 font-bold">Risk filters</h2><button onClick={() => setActiveCategory("all")} className={`mb-2 w-full rounded-xl px-3 py-2 text-left text-sm ${activeCategory === "all" ? "bg-cyan-300 text-slate-950" : "text-slate-300 hover:bg-white/5"}`}>All categories <span className="float-right">{hunks.length}</span></button>{categories.map((category) => <button key={category} onClick={() => setActiveCategory(category)} className={`mb-1 w-full rounded-xl px-3 py-2 text-left text-sm capitalize ${activeCategory === category ? "bg-cyan-300 text-slate-950" : "text-slate-300 hover:bg-white/5"}`}><span className="mr-2 text-cyan-300">{catIcon[category]}</span>{category}<span className="float-right">{hunks.filter((h) => h.category === category).length}</span></button>)}<label className="mt-4 flex items-center gap-2 border-t border-slate-700 pt-4 text-xs text-slate-300"><input checked={aiOn} onChange={(e) => setAiOn(e.target.checked)} type="checkbox" /> Sharpen explanations with AI</label></aside>
      <section><div className="mb-3 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-black">Review queue</h2><p className="text-xs text-slate-400">{visible.length} hunk{visible.length === 1 ? "" : "s"} matching your view</p></div><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search paths or diff…" className="rounded-xl border border-slate-700 bg-slate-950/45 px-3 py-2 text-sm placeholder:text-slate-500" /></div>{visible.length ? <div className="space-y-4">{visible.map((h) => <HunkCard key={h.id} hunk={h} decision={decisions[h.id] ?? "pending"} comment={comments[h.id] ?? ""} aiOn={aiOn} aiReason={aiReasons[h.id]} onDecision={decide} onComment={(value) => setComments((all) => ({ ...all, [h.id]: value }))} onSharpen={sharpen} />)}</div> : <div className="glass rounded-3xl p-10 text-center text-slate-400"><p className="text-3xl">⌕</p><p className="mt-3 font-bold text-slate-200">No hunks match this view</p><p className="mt-1 text-sm">Clear the search or choose another risk category.</p></div>}</section>
      <aside className="glass h-fit rounded-3xl p-5 xl:sticky xl:top-5"><h2 className="font-bold">Recent review activity</h2><div className="mt-4 space-y-4 text-sm">{[...hunks].slice(0, 3).map((h) => <div key={h.id} className="border-l-2 border-cyan-300/60 pl-3"><p className="font-bold">{h.path}</p><p className="mt-1 text-xs text-slate-400">{decisions[h.id] && decisions[h.id] !== "pending" ? `Marked ${decisions[h.id].replace("_", " ")}` : `${h.assessment.level} risk detected`}</p></div>)}</div><div className="mt-6 rounded-2xl bg-cyan-300/10 p-4"><p className="text-xs font-bold text-cyan-200">DETERMINISTIC ENGINE</p><p className="mt-1 text-xs leading-5 text-slate-300">GitHub changes and AI wording never alter the score. Path and patch signals always do.</p></div></aside>
    </section>
    {requesting && requestGuide && <div className="fixed inset-0 z-20 grid place-items-end bg-slate-950/70 p-4 backdrop-blur-sm sm:place-items-center" role="dialog" aria-modal="true" aria-labelledby="changes-title"><section className="glass w-full max-w-lg rounded-3xl p-6"><div className="flex justify-between gap-4"><div><p className="text-xs font-bold tracking-[.16em] text-rose-300">REQUEST CHANGES</p><h2 id="changes-title" className="mt-1 text-xl font-black">Structured reviewer guidance</h2></div><button onClick={() => setRequesting(null)} aria-label="Close request changes panel" className="text-xl text-slate-300">×</button></div><p className="mt-2 text-sm text-slate-400">{requesting.path}</p><div className="mt-5 grid gap-4"><Panel label="Severity" value={requestGuide.severity} /><Panel label="Reviewer comment" value={requestGuide.reviewerComment} /><Panel label="Suggested fix" value={requestGuide.suggestedFix} /></div><button onClick={() => setRequesting(null)} className="mt-6 w-full rounded-xl bg-cyan-300 py-3 font-bold text-slate-950">Keep request changes</button></section></div>}
  </main>;
}
function Stat({ label, value, accent }: { label: string; value: number; accent: string }) { return <div className="glass lift rounded-2xl p-4"><p className="text-xs font-bold uppercase tracking-wide text-slate-400">{label}</p><p className={`mt-2 text-3xl font-black ${accent}`}>{value}</p></div>; }
function Panel({ label, value }: { label: string; value: string }) { return <div><p className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 rounded-xl border border-slate-700 bg-slate-950/50 p-3 text-sm leading-6 text-slate-200">{value}</p></div>; }
function HunkCard({ hunk, decision, comment, aiOn, aiReason, onDecision, onComment, onSharpen }: { hunk: ReviewHunk; decision: Decision; comment: string; aiOn: boolean; aiReason?: string; onDecision: (h: ReviewHunk, d: Decision) => void; onComment: (value: string) => void; onSharpen: (h: ReviewHunk) => void }) { return <article className="glass lift rounded-3xl p-5"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full border border-cyan-300/20 bg-cyan-300/10 px-2.5 py-1 text-xs font-bold capitalize text-cyan-100">{catIcon[hunk.category]} {hunk.category}</span><span className={`rounded-full border px-2.5 py-1 text-xs font-bold uppercase ${tone[hunk.assessment.level]}`}>{hunk.assessment.level} · {hunk.assessment.score}</span><span className="ml-auto text-xs capitalize text-slate-500">{decision.replace("_", " ")}</span></div><h3 className="mt-4 font-mono text-sm font-bold text-slate-200">{hunk.path}</h3><pre className="mt-3 rounded-2xl border border-slate-800 bg-[#050b15] p-4 text-xs leading-6 text-slate-300">{hunk.diff}</pre><div className="mt-4 rounded-xl border border-slate-700/70 bg-slate-950/35 p-3 text-sm leading-6 text-slate-300"><strong className="text-cyan-200">Why it matters · </strong>{aiReason ?? hunk.assessment.reason}</div><div className="mt-4 flex flex-wrap gap-2"><Action label="Approve" ariaLabel={`Approve ${hunk.id}`} style="bg-emerald-400/15 text-emerald-100 hover:bg-emerald-400/25" onClick={() => onDecision(hunk, "approved")} /><Action label="Redirect" style="bg-orange-400/15 text-orange-100 hover:bg-orange-400/25" onClick={() => onDecision(hunk, "rejected")} /><Action label="Request changes" style="bg-rose-400/15 text-rose-100 hover:bg-rose-400/25" onClick={() => onDecision(hunk, "request_changes")} /><Action label="Comment" style="bg-slate-700/50 text-slate-100 hover:bg-slate-700" onClick={() => onDecision(hunk, "commented")} />{aiOn && <Action label="✦ Sharpen" style="border border-cyan-300/30 text-cyan-100 hover:bg-cyan-300/10" onClick={() => onSharpen(hunk)} />}</div>{decision === "commented" && <label className="mt-4 block text-sm font-bold text-slate-300">Reviewer note<textarea value={comment} onChange={(e) => onComment(e.target.value)} className="mt-2 block w-full rounded-xl border border-slate-700 bg-slate-950/50 p-3 font-normal" rows={2} /></label>}</article>; }
function Action({ label, ariaLabel, style, onClick }: { label: string; ariaLabel?: string; style: string; onClick: () => void }) { return <button onClick={onClick} className={`rounded-xl px-3 py-2 text-xs font-bold transition ${style}`} aria-label={ariaLabel ?? label}>{label}</button>; }
*/
